@startmindmap
!theme vibrant

<style>

node {
    Padding 12
    Margin 3
    LineColor green
    LineThickness 3.0
}

rootNode {
    LineStyle 8.0;3.0
    LineColor green
    BackgroundColor lightgreen
    LineThickness 3.0
    RoundCorner 0
    Shadowing 5
}

leafNode {
    LineStyle 1
    LineColor red
    LineThickness 1.0
    RoundCorner 20
    Padding 3
}

arrow {
    LineStyle 3
    LineThickness 1
    LineColor green
}
</style>


caption (c) Вот так вот, ребяты
title Большая карта Фриловода [LR Freelander Mind Map]

header
v.0.5
endheader




*:Land Rover 
Freelander 1
;

** Информация о Freelander
*** Форумы 
****_ [[https://lrfreelander.ru/ LRFreelander.ru (LR Freelander club (Основан в 2013 г. Более 7000 учатсников]]
****_ [[https://lrfreelander.spybb.ru/ lrfreelander.spybb.ru Land Rover эксплуатация и ремонт]]
****_ [[http://lr-club.com/index.php?showforum=83 LRclub.ru]]
****_ [[https://land-rover-forum.ru/ land-rover-forum.ru Lan Rover Форум Клуб]]
*** Каналы
*** Сайты
*** Группы
**** VK
*****_ [[https://vk.com/club114145226 Клуб любителей Land Rover Freelander 1 (Основан в 2017 г. Более 1800 участников)]]
*****_ [[https://vk.com/club25363067 LAND ROVER FREELANDER CLUB (Более 700 участников)]]


** Двигатель 1.8
*** Общие сведения
****_ Тип
*****_ 1,8 л, бензиновый, 16-клапанный, 2 верхних распределительных вала
****_ Расположение цилиндров
*****_ 4 цилиндра, расположенные в ряд; нумерация цилиндров от передней части двигателя
****_ Диаметр цилиндра
*****_ 80,00 мм
*****_ 3,150 дюйма
****_ Ход поршня
*****_ 89,30 мм
*****_ 3,516 дюйма
****_ Рабочий объем
*****_ 1796 см3
*****_ 109,59 дюймов3
****_ Порядок работы
*****_ 1-3-4-2
****_ Степень сжатия
*****_ 10,5 :1 ± 0,5 :1
****_ Направление вращения
*****_ По часовой стрелке, если смотреть с передней части двигателя
****_ Максимальная мощность
*****_ 	88 КВт (118 л.с.) при 5500 об/мин
****_ Максимальный крутящий момент
*****_ 165 Нм (223,7 фунт-футов) при 2750 об/мин
****_ Частота вращения холостого хода
*****_ 	775 ± 50 об/мин
****_ Максимальная частота вращения вала
*****_ 6750 об/мин
****_ Масса(с полным оборудованием,заполненными системами смазки и охлаждения)
*****_ 	108 кг
**** Габаритные размеры
*****_ Длина (номинальная)
******_ 654 мм
******_ 25,75 дюйма
*****_ Ширина (номинальная)
******_ 600 мм
******_ 23,62 дюйма
*****_ Высота (номинальная)
******_ 615 мм
******_ 24,21 дюйма

***_ [[https://freelanderos.ru/man/1/power/engine_k1_8/engine_and_transmission.html <&book>Двигатель и коробка передач демонтаж]]


*** Блок цилиндров
**** Характеристики
*****_ Материал
******_ Алюминиевый сплав
*****_ Тип гильз цилиндров
******_ 	Мокрые, с нижней ребристой частью, устанавливаемые на скользящей посадке в нижнюю часть блока цилиндров
*****_ Диаметр гильз цилиндров
******_ Класс А с красной маркировкой
*******_ 80 000 - 80,015 мм
*******_ 3,1496 - 3,1501 дюймов
******_ Класс В с синей маркировкой
*******_ 80,016 - 80,030 мм
*******_ 3,1502 - 3,1508 дюймов


**** Головка блока цилиндров
***** Характеристики
******_ Материал
*******_  Алюминиевый сплав
******_ Высота головки блока
*******_  Новая
********_ 118,95 - 119,05 мм
********_ 4,683 - 4,687 дюймов
*******_  Припуск на обработку привалочной плоскости
********_ 0,20 мм
********_ 0,008 дюйма

***** Прокладка ГБЦ
****** Замена прокладки ГБЦ
*******_ [[https://freelanderos.ru/man/1/power/engine_k1_8/cylinder_head_gasket.html <&book>Прокладка головки блока цилиндров (Фрилендер 1) Демонтаж,замена]]
*******_ [[https://lrfreelander.ru/viewtopic.php?id=1286 <&people>1. LRF Большая Подробная ветка о замене прокладки  ГБЦ]]
*******_ [[https://lrfreelander.ru/viewtopic.php?id=378 <&people>2. LRF Большая Подробная ветка о замене прокладки  ГБЦ В картинках]]
*******_ [[https://lrfreelander.ru/viewtopic.php?id=233 <&people>3. LRF Большая Подробная ветка Замена прокладки ГБЦ, перегрев, ремонт движка]]
*******_ [[https://lrfreelander.ru/viewtopic.php?id=5643 <&people>4. LRF Большая Подробная ветка Замена прокладки ГБЦ, перегрев, ремонт движка II]]
*******_ [[https://lrfreelander.ru/viewtopic.php?id=4407 <&people>5. LRF Большая Подробная ветка Замена прокладки ГБЦ том2]]
******[#FF4C5B] <&warning*2>
*******_ [[https://lrfreelander.ru/viewtopic.php?id=2361#p49842 <&person>Маслянный щуп в майонезе, уходит литр антифриза в день]]
'****** Проблемы прокладки ГБЦ
*******_ [[https://lrfreelander.ru/viewtopic.php?id=1410 <&people>Проблема с обтяжкой прокладки ГБЦ]]
*******_ [[https://lrfreelander.ru/viewtopic.php?id=6358 <&people>После замены прокладки ГБЦ пошли газы в систему охлаждения]]
*******_ [[https://lrfreelander.ru/viewtopic.php?id=8218 <&people>После замены прокладки кипит]]
*******_ [[https://lrfreelander.ru/viewtopic.php?id=8570#p228966 <&person>После замены прокладки троит двигатель]]
***** Клапанная крышка
******_ [[https://freelanderos.ru/man/1/power/engine_k1_8/valve_cover_gasket.html <&book>Прокладка клапанной крышки]]
***** Болты ГБЦ
******[#lightgreen] <&list> WAM2293L
******_ [[https://lrfreelander.ru/viewtopic.php?id=5050 <&people>Ветка: Окончательный момент затяжки болтов ГБЦ]]
******_ [[https://lrfreelander.ru/viewtopic.php?id=7510 <&people>Ветка: Целесообразность замены болтов ГБЦ]]
***** Распредвалы
******_ [[https://freelanderos.ru/man/1/power/engine_k1_8/front_oil_seal_exhaust_camshaft.html <&book>Передний сальник выпускного распределительного вала]]
******_ [[https://freelanderos.ru/man/1/power/engine_k1_8/rear_exhaust_camshaft_oil_seal.html <&book>Задний сальник выпускного распределительного вала]]
******_ [[https://freelanderos.ru/man/1/power/engine_k1_8/rear_intake_camshaft_oil_seal.html <&book>Задний сальник впускного распределительного вала]]
******_ [[https://freelanderos.ru/man/1/power/engine_k1_8/integral_cover_camshafts.html <&book>Интегральная крышка распредвалов: герметизация]]
***** Маслосъемные колпачки
******_ [[https://freelanderos.ru/man/1/power/engine_k1_8/stem_seal.html <&book>Маслосъёмные колпачки - снитие и установка]]
**** Поршневая группа
*****_ [[https://freelanderos.ru/man/1/power/piston_k1_8/removing_and_installing.html <&book>Снятие и установка поршневой группы]]
**** Шатунные вкладыши
*****_ [[https://freelanderos.ru/man/1/power/engine_k1_8/replacing_connecting_rod_bearings.html <&book>Замена шатунных вкладышей]]

**** Коленчатый вал
*****_ Осевой зазор коленчатого вала
******_ 0,10 - 0,25 мм (0,004 - 0,010 дюймов)
******_ Допускается без замены	0,34 мм (0,013 дюйма)
*****_ Коренная шейка
******_ Диаметр коренной шейки
*******_ 47,986 - 48,007 мм (1,8892 - 1,8900 дюймов)
*******_ Максимальное отклонение от круглой формы	0,010 мм (0,0004 дюйма)
******_ Допуск на диаметр коренной шейки
*******_ - Класс 1	48 000 - 48,007 мм (1,8898 - 1,8900 дюймов)
*******_ - Класс 2	47,993 - 48,000 мм (1,8895 - 1,8898 дюймов)
*******_ - Класс 3	47,986 - 47,993 мм (1,8892 - 1,8895 дюймов)
*****_ Шатунные шейки
******_ Диаметр шатунных шеек коленчатого вала
*******_ 47,986 - 48,007 мм (1,8892 - 1,8900 дюймов)
*******_ - Максимальное отклонение от круглой формы	0,010 мм (0,0004 дюйма)
******_ Допуск на диаметр шатунных шеек коленчатого вала
*******_ - Класс А	48 000 - 48,007 мм (1,8898 - 1,8900 дюймов)
*******_ - Класс В	47,993 - 48,000 мм (1,8895 - 1,8898 дюймов)
*******_ - Класс С	47,986 - 47,993 мм (1,8892 - 1,8898 дюймов)
*****_ [[https://freelanderos.ru/man/1/power/engine_k1_8/crankshaft_pulley.html <&book>Шкив коленчатого вала]]
*****_ [[https://freelanderos.ru/man/1/power/engine_k1_8/front_crankshaft_oil_seal.html <&book>Передний сальник коленчатого вала]]
*****_ [[https://freelanderos.ru/man/1/power/engine_k1_8/rear_crankshaft_oil_seal.html <&book>Задний сальник коленчатого вала]]
*****_ [[https://freelanderos.ru/man/1/power/piston_k1_8/front_crankshaft_seal.html <&book>Передний сальник коленвала]]
*****_ [[https://freelanderos.ru/man/1/power/piston_k1_8/replacing_crankshaft_rear_oil_seal.html <&book>Замена заднего сальника коленчатого вала]]
*****_ [[https://freelanderos.ru/man/1/power/piston_k1_8/crankshaft_and_main_bearings.html <&book>Коленчатый вал и коренные подшипники]]
***** Коренные подшипники коленвала
******_ Количество
*******_ 5
******_ Тип
*******_ На стальной основе
*******_ беговая поверхность из алюминия с оловом
*******_ прорезь для масла в верхней части
*******_ вкладыши крышки шатуна
********_ гладкие
******_ Зазор в подшипниках
*******_ 0,02 - 0,05 мм
*******_ 0,0008 - 0,0020 дюймов
******_ Упорные шайбы
*******_ Половинки на 3-й опоре коленчатого вала
******_ Толщина половинок упорной шайбы
*******_ 2,61 - 2,65 мм
*******_ 0,1028 - 1,043 дюймов
***** Подшипники шатунных шеек коленчатого вала
******_ Зазор в подшипниках
*******_ 0,021 - 0,049 мм
*******_ 0,0008 - 0,0019 дюймов
******_ Осевой люфт шатунного подшипника
*******_ 0,10 - 0,25 мм
*******_ 0,004 - 0,010 дюймов
**** Шатуны
*****_ Тип
******_ Нижняя головка с горизонтальным разъемом
******_ Верхняя головка неразъемная
*****_ Расстояние между осями верхней и нижней головок
******_ 133,05 - 133,15 мм
******_ 5,238 - 5,242 дюймов
**** Поршни
*****_ Тип
******_ Из алюминиевого сплава, покрытые оловом, соединение с выступом поршневого пальца температурным расширением
*****_ Диаметр поршня
******_ - Класс А
*******_ 79,975 - 79,990 мм
*******_ 3,1486 - 3,1492 дюймов
******_ - Класс В
*******_ 79,991 - 80,005 мм
*******_ 3,1492 - 3,1498 дюймов
*****_ Радиальный зазор
******_ 0,01 - 0,04 мм
******_ 0,0004 - 0,0016 дюймов
*****_ Максимальное отклонение от круглой формы
******_ 0,30 мм
******_ 0,012 дюйма
***** Поршневые кольца

***** Поршневые пальцы
******_ Тип
*******_ Полуплавающего типа, с выступом в упорной части
******_ Посадка в верхней головке шатуна
******_ - Диаметр (красная маркировка)
*******_ 17,997 - 18,000 мм
*******_ 0,7085 - 0,7087 дюймов
******_ - Диаметр (зеленая маркировка)
*******_ 17,994 - 17,997 мм
*******_ 0,7084 - 0,7087 дюймов
******_ - Длина
*******_ 52,3 - 52,6 мм
*******_ 2,06 - 2,07 дюймов



**** Маховик
*****_ [[https://freelanderos.ru/man/1/power/engine_k1_8/flywheel.html <&book>Маховик - снятие и установка]]


*** Ремень ГРМ
****_ [[https://freelanderos.ru/man/1/power/engine_k1_8/timing_belt.html <&book>Ремень ГРМ - снятие и установка]]
****_ [[https://freelanderos.ru/man/1/power/engine_k1_8/upper_timing_cover.html <&book>Верхняя крышка привода ГРМ]]
****_ [[https://freelanderos.ru/man/1/power/engine_k1_8/back_cover_of_timing_belt.html <&book>Задняя крышка ремня ГРМ]]
****_ [[https://lrfreelander.ru/viewtopic.php?id=166 <&people>Выбор ремня ГРМ от 97... 1,8 145-зуб]]
**** Замена ремня ГРМ
*****_ [[https://freelanderos.ru/man/1/power/engine_k1_8/timing_belt.html <&book>Ремень ГРМ - снятие и установка]]
*****_ [[https://www.youtube.com/watch?v=CM5oA2X03z8 <&video>Видео о замене ремня ГРМ]]
*****_ [[https://lrfreelander.ru/viewtopic.php?id=1 <&people>Большая подробная ветка о замене ремня ГРМ]]
******_ [[https://lrfreelander.ru/viewtopic.php?id=1#p14226 <&person>Важно обратить внимание!]]
******_ [[https://lrfreelander.ru/viewtopic.php?id=1&p=3#p119053 <&person>Самодельное приспособление для откручивания шкива коленвала]]
******_ [[https://lrfreelander.ru/viewtopic.php?id=1&p=5#p211842 <&person>Фото правильной установки ремня ГРМ]]
******_ [[https://lrfreelander.ru/viewtopic.php?id=8572#p229025 <&person>Порядок установки ремня ГРМ]]
******_ [[https://s3.uploads.ru/t/ubxsg.jpg <&image>Автоматический и ручной ролики разные, взаимоНезаменяемые!]]
******_ [[https://s3.uploads.ru/Sof9e.jpg <&image>Схема установки меток!]]


*** Система смазки
****_ [[https://freelanderos.ru/man/1/power/engine_k1_8/oil_pump.html <&book>Масляный насос - снятие и установка]]
****_ [[https://freelanderos.ru/man/1/power/piston_k1_8/bulkhead_oil_pump.html <&book>Переборка масляного насоса]]
****_ [[https://freelanderos.ru/man/1/power/engine_k1_8/sealing_of_oil_pan.html <&book>Герметизация масляного поддона]]
****_ [[https://freelanderos.ru/man/1/power/piston_k1_8/pan.html <&book>Поддон - снятие и установка]]
****_ [[https://freelanderos.ru/man/1/power/engine_k1_8/oil_pressure_switch.html <&book>Контактный датчик давления масла]]
****_ [[https://freelanderos.ru/man/1/power/engine_k1_8/reducing_valve_lubrication_system.html <&book>Редукционный клапан системы смазки]]
****_ [[https://freelanderos.ru/man/1/power/engine_k1_8/oil_temperature_sensor.html <&book>Датчик температуры масла]]
*** Гидрокомпенсаторы

*** Управление двигателем
**** Свечи зажигания
***** Характеристики
******_ Тип 
*******_ NLP100290
******_ Зазор
*******_ 1,0 мм ± 0,05 мм
*******_ 0,039 дюйма ± 0,002 дюйма
*****_ [[https://freelanderos.ru/man/1/power/mems/spark_plug.html <&book>Свечи зажигания]]
*****[#FF4C5B] <&warning*2>
****** Чёрные свечи
*******_ [[https://lrfreelander.ru/viewtopic.php?id=7815#p219699 <&people>Троит на холостых, свечи чёрные]]
**** Катушка зажигания
***** Характеристики
******_ Изготовитель
*******_ Nippon Denso
********[#lightgreen] <&list> NEC100730
********_ для vin 5A000001 - 
*********[#lightgreen] <&list> NEC000120
******_ Тип
*******_ 2 катушки с двойными обмотками высокого напряжения, с клеммой на верхней части, для 1-го и 4-го цилиндров и для 2-го и 3-го цилиндров
******_ Сопротивление первичной обмотки (номинальное)
*******_ 0,7 Ом
******_ Сопротивление вторичной обмотки (номинальное)
*******_ 10 Ом
******_ Система впрыскивания топлива
*******_ Топливная рампа без возврата топлива, распределенный впрыск с электронным управлением блоком ECM
******_ Контроллер
*******_ MEMS 3 бесконтактного зажигания, электронный, полностью программируемая система управления двигателем
*****_ [[https://freelanderos.ru/man/1/power/mems/ignition_coil.html <&book>Катушка зажигания]]
**** Распределитель зажигания (Трамблер)
*****[#yellow] <&info>Запасные крышку трамблера и бегунок лучше всегда возить с собой!
***** Кышка трамблера
******[#lightgreen] <&list> NJD10010
******[#FF4C5B] <&warning*2>
*******_ [[https://lrfreelander.ru/viewtopic.php?id=7815#p246287 <&people>Неисправность крышки трамблера]]
***** Бегунок
******[#lightgreen] <&list> NJD10003
**** Блок управления двигателем (ECM)
*****_ [[https://freelanderos.ru/man/1/power/mems/ecm.html <&book>Блок управления двигателем (ECM)]]
**** Регулятор холостого хода (IAC)
*****_ [[https://freelanderos.ru/man/1/power/mems/iac.html <&book>Регулятор холостого хода (IAC)]]
**** Датчики
***** Датчик температуры ОЖ
******_ [[https://freelanderos.ru/man/1/power/mems/ect.html <&book>Датчики: датчик температуры охлаждающей жидкости (ECT)]]
***** Датчик положения коленвала
******_ [[https://freelanderos.ru/man/1/power/mems/ckp.html <&book>Датчики: датчик положения коленчатого вала (CKP)]]
***** Датчик положения дроссельной заслонки
******_ [[https://freelanderos.ru/man/1/power/mems/throttle_position_sensor.html <&book>Датчик положения дроссельной заслонки]]
***** Датчик положения распредвала
******_ [[https://freelanderos.ru/man/1/power/mems/cmp.html <&book>Датчики: датчик положения распределительного вала (CMP)]]
***** Датчик педали газа
******_ [[https://freelanderos.ru/man/1/power/mems/contact_pedal_position_sensor.html <&book>Контактный датчик положения педали]]
***** Датчик абсолютного давления
******_ [[https://freelanderos.ru/man/1/power/mems/map.html <&book>Датчик абсолютного давления во впускном коллекторе (MAP)]]
***** Датчик положения педали акселлератора (датчик педали газа)
******_ [[https://freelanderos.ru/man/1/chassis/brake/accelerator_pedal_position_sensor.html <&book>Датчик положения педали акселератора (лягушка)]]
*** Опоры
****_ [[https://freelanderos.ru/man/1/power/engine_k1_8/bracket_right_engine_mount_assembly.html <&book>Кронштейн правой опоры двигателя в сборе]]
****_ [[https://freelanderos.ru/man/1/power/engine_k1_8/right_hydro_engine.html <&book>Гидроопора двигателя правая]]

*** Топливная система
****_ [[https://freelanderos.ru/man/1/power/petrol_k1_8/depressurization_fuel_supply_system.html <&book>Сброс давления в системе подачи топлива]]
****_ [[https://freelanderos.ru/man/1/power/petrol_k1_8/measurement_pressure_in_fuel_supply.html <&book>Измерение давления в системе подачи топлива]]
****_ [[https://freelanderos.ru/man/1/power/petrol_k1_8/cable_throttle_control.html <&book>Трос управления дроссельной заслонкой - проверка и регулировка]]
****_ [[https://freelanderos.ru/man/1/power/petrol_k1_8/air_filter.html <&book>Фильтр очистки воздуха]]
****_ [[https://freelanderos.ru/man/1/power/petrol_k1_8/air_filter_element.html <&book>Фильтрующий элемент воздушного фильтра]]
****_ [[https://freelanderos.ru/man/1/power/petrol_k1_8/inertia_switch_fuel_cut.html <&book>Инерционный выключатель отсечки топлива]]
****_ [[https://freelanderos.ru/man/1/power/petrol_k1_8/front_oxygen_sensor.html <&book>Передний кислородный датчик]]
****_ [[https://freelanderos.ru/man/1/power/petrol_k1_8/maf.html <&book>Датчик массового расхода воздуха (MAF)]]
****_ [[https://freelanderos.ru/man/1/power/petrol_k1_8/fuel_pump_relay.html <&book>Реле топливного насоса]]
****_ [[https://freelanderos.ru/man/1/power/petrol_k1_8/throttle_tube.html <&book>Дроссельный патрубок]]
****_ [[https://freelanderos.ru/man/1/power/petrol_k1_8/rear_oxygen_sensor.html <&book>Задний кислородный датчик]]
****_ [[https://freelanderos.ru/man/1/power/petrol_k1_8/switch_resume_mode_since_may.html <&book>Выключатель возобновления режима: с мая 2004 года]]
****_ [[https://freelanderos.ru/man/1/power/petrol_k1_8/multifunction_switch.html <&book>Многофункциональный выключатель]]

**** Форсунки
***** Характеристики
******_ Рабочее давление
*******_ 3,5 бара
*******_ 50,8 фунтов/дюйм2
******_ Производительность топливного насоса
*******_ 117 г/мин при давлении 3,0 бар
*******_ 4,13 унций/мин при 43,5 фунт/дюйм2
******_ Привод клапанов
*******_ Саморегулирующимися гидравлическими толкателями малой массы, приводимыми непосредственно распредвалами
******_ Выполняемые нормы по содержанию вредных веществ в отработавших газах
*******_ ECD3
*****_ [[https://freelanderos.ru/man/1/power/petrol_k1_8/nozzles.html <&book>Форсунки (комплект) - снятие и установка]]

**** Топливный бак
*****_ [[https://freelanderos.ru/man/1/power/petrol_k1_8/drain_fuel_from_tank.html <&book>Слив топлива из бака]]
*****_ [[https://freelanderos.ru/man/1/power/petrol_k1_8/fuel_tank.html <&book>Топливный бак: кроме стран Североамериканского рынка]]
*****_ [[https://freelanderos.ru/man/1/power/petrol_k1_8/fuel_tank_american_market.html <&book>Топливный бак: страны Североамериканского рынка]]
*****_ [[https://freelanderos.ru/man/1/power/petrol_k1_8/filler_pipe.html <&book>Заливная труба - снятие и установка]]

***** Топливный насос
******_ [[https://www.freelanderos.ru/man/1/power/petrol_k1_8/electric_fuel_pump.html <&book>Электробензонасос - снятие и установка (Фрилендер 1)]]

****** Мотор насоса
*******[#yellow] <&info>Перед смертью обычно моторчик громко гудит
*******_ [[https://lrfreelander.ru/viewtopic.php?id=5 <&people>Форум: Большая подробная тема о ТН, замена мотора насоса на Бош от Ваза]]
*******[#FF4C5B] <&warning*2>
********_ [[https://lrfreelander.ru/viewtopic.php?id=15830 <&bug>Топливный насос работает постоянно (при включенном зажигании)]]
*********_ [[http://freelander.spybb.ru/viewtopic.php?id=337#p15873 <&wrench>Некорректно работает дополнительная сигнализация]]
*********_ [[http://freelander.spybb.ru/viewtopic.php?id=337#p15881 <&wrench>Глючит аварийный топливный датчик]]
****** Топливный фильтр
*******_ [[https://www.freelanderos.ru/man/1/power/petrol_k1_8/main_filter_cleaning_fuel.html <&book>Замена основного фильтра очистки топлива (Фрилендер 1)]]
*******_ [[http://freelander.spybb.ru/viewtopic.php?id=9#p510 <&people>Замена фильтра тонкой очистки топлива (бензиновые двигатели)]]
*******_ [[https://vk.com/topic-114145226_35264548 <&sun>Замена фильтра тонкой очистки топлива (бензиновые двигатели)]]

****** Регулятор давления
****** Датчик уровня топлива

*** Навесное оборудование
**** Стартер
*****_ См.Электрооборудование - Навесное оборудование - Стартер
**** Генератор
*****_ См.Электрооборудование - Навесное оборудование - Генератор
**** Приводные ремни
*****_ [[https://freelanderos.ru/man/1/electrics/engine_start/belt_attachment_k1_8.html <&book>Ремень привода навесного оборудования - двигатель K1.8]]
*****_ [[https://freelanderos.ru/man/1/electrics/engine_start/belt_attachment_k1_8_with_conditioning.html <&book>Ремень привода навесного оборудования - двигатель K1.8 с кондиционером]]
*****_ [[https://freelanderos.ru/man/1/electrics/engine_start/belt_attachment_k1_8_without_conditioning.html <&book>Ремень привода навесного оборудования - двигатель K1.8 без кондиционера]]



***[#FF4C5B] <&warning*2>
**** Не заводится
**** Плохо заводится
*****_ [[https://lrfreelander.ru/viewtopic.php?id=7815#p217873 <&bug>Заводится, дёргается, не развивает обороты]]
******_ [[https://lrfreelander.ru/viewtopic.php?id=7815#p217898 <&person>Не работает датчик температуры]]
*******_ Плохо работает бензонасос
*******_ Плохо работает зажигание
********_ Проблемы с крышкой трамблера
********_ Проблемы с бегунком
********_ Проблемы со свечами
********_ Проблемы с высоковольтными проводами
********_ Проблемы с катушкой (катушками)
*****_ [[https://lrfreelander.ru/viewtopic.php?id=5#p294 <&bug>Плохо заводится на холодную, на ходу при ускорении плохо набирает обороты]]
******_ Неисправность бензонасоса
*****_ [[https://lrfreelander.ru/viewtopic.php?id=7815#p220937 <&bug>Пропадает тяга под нагрузкой]]
******_ [[https://lrfreelander.ru/viewtopic.php?id=7815#p220937 <&person>Проблемы с МАП сенсором]]
**** Троит
*****_ [[https://lrfreelander.ru/viewtopic.php?id=7815#p219699 <&people>Троит на холостых, свечи чёрные]]
*****_ [[https://lrfreelander.ru/viewtopic.php?id=7815#p246287 <&people>Заводится нормально, после прогрева троит]]
****** см. Двигатель - Управление двигателем - Распределитель зажигания - Крышка трамблера - <&warning>

** Двигатель KV6
***_ [[https://freelanderos.ru/man/1/electrics/engine_start/belt_attachment_engine_kv6.html <&book>Ремень привода навесного оборудования - двигатель KV6]]
** Двигатель Td4
***_ [[https://freelanderos.ru/man/1/electrics/engine_start/belt_attachment_td4.html <&book>Ремень привода навесного оборудования - двигатель Td4]]
***_ [[https://freelanderos.ru/man/1/electrics/engine_start/tensioner_td4.html <&book>Натяжитель - Ремень привода навесного оборудования - Td4]]


** Трансмиссия
*** Автоматическая коробка
****_ [[https://freelanderos.ru/man/1/power/automatic/replacing_hydraulic_fluid.html <&book>Замена рабочей жидкости в коробке]]
****_ [[https://freelanderos.ru/man/1/power/automatic/adjustment_cable_selector.html <&book>Регулировка троса селектора]]
****_ [[https://freelanderos.ru/man/1/power/automatic/selector_housing.html <&book>Корпус селектора - снятие и установка]]
****_ [[https://freelanderos.ru/man/1/power/automatic/handle_selector.html <&book>Рукоятка селектора - снятие и установка]]
****_ [[https://freelanderos.ru/man/1/power/automatic/cable_selector.html <&book>Трос селектора - снятие и установка]]
****_ [[https://freelanderos.ru/man/1/power/automatic/position_indicator_of_selector.html <&book>Указатель положения селектора: автомобили до мая 2003 года]]
****_ [[https://freelanderos.ru/man/1/power/automatic/position_indicator_of_selector_after_may_2004.html <&book>Указатель положения селектора: автомобили после мая 2004 года]]
****_ [[https://freelanderos.ru/man/1/power/automatic/switch_immobilizer.html <&book>Выключатель блокировки запуска двигателя]]
****_ [[https://freelanderos.ru/man/1/power/automatic/control_unit.html <&book>Блок управления (ECU)]]
****_ [[https://freelanderos.ru/man/1/power/automatic/gland_torque_converter.html <&book>Сальник гидротрансформатора]]
****_ [[https://freelanderos.ru/man/1/power/automatic/transmission_with_engine_kv6.html <&book>Коробка передач с двигателем KV6 (двигатель с коробкой сняты)]]
****_ [[https://freelanderos.ru/man/1/power/automatic/transmission_kv6.html <&book>Коробка передач: автомобили с двигателем KV6 - снятие и установка]]
****_ [[https://freelanderos.ru/man/1/power/automatic/transmission_td4.html <&book>Коробка передач: автомобиль с двигателем Td4 - снятие и установка]]
****_ [[https://freelanderos.ru/man/1/power/automatic/sealing_bottom_of_gearbox.html <&book>Герметизация днища коробки передач]]
****_ [[https://freelanderos.ru/man/1/power/automatic/ventilated_cooling_heat_exchanger_working_fluid_td4.html <&book>Обдуваемый теплообменник охлаждения рабочей жидкости: автомобили с двигателем Td4]]
****_ [[https://freelanderos.ru/man/1/power/automatic/heat_exchanger_cooling_working_fluid_td4.html <&book>Теплообменник охлаждения рабочей жидкости: автомобили с двигателем Td4]]
****_ [[https://freelanderos.ru/man/1/power/automatic/heat_exchanger_cooling_working_fluid_kv6.html <&book>Теплообменник охлаждения рабочей жидкости: автомобили с двигателем KV6]]
****_ [[https://freelanderos.ru/man/1/power/automatic/hose_heat_exchanger_cooling_hydraulic_fluid.html <&book>Шланги теплообменника охлаждения рабочей жидкости]]


*** Механическая коробка
****_ [[https://freelanderos.ru/man/1/power/mechanical/changing_transmission_oil_in_pg1.html <&book>Замена трансмиссионного масла в коробке PG1]]
****_ [[https://freelanderos.ru/man/1/power/mechanical/transmission_pg1.html <&book>Коробка передач PG1 - снятие и установка]]
****_ [[https://freelanderos.ru/man/1/power/mechanical/gland_selector_shaft_pg1.html <&book>Сальник штока выбора передач PG1]]
****_ [[https://freelanderos.ru/man/1/power/mechanical/reversing_light_switch_pg1.html <&book>Выключатель фонаря заднего хода PG1]]
****_ [[https://freelanderos.ru/man/1/power/mechanical/contact_sensor_activate_first_gear_pg1.html <&book>Контактный датчик включения первой передачи PG1]]
****_ [[https://freelanderos.ru/man/1/power/mechanical/changing_transmission_oil_in_getrag.html <&book>Замена трансмиссионного масла в коробке GETRAG]]
****_ [[https://freelanderos.ru/man/1/power/mechanical/back_cover_getrag.html <&book>Задняя крышка GETRAG - снятие и установка]]
****_ [[https://freelanderos.ru/man/1/power/mechanical/selection_mechanism_getrag.html <&book>Механизм выбора передач GETRAG: верхняя тяга и сферические шарниры]]
****_ [[https://freelanderos.ru/man/1/power/mechanical/getrag_transmission.html <&book>Коробка передач GETRAG - снятие и установка]]
****_ [[https://freelanderos.ru/man/1/power/mechanical/input_shaft_lip_seal_getrag.html <&book>Сальник первичного вала GETRAG]]
****_ [[https://freelanderos.ru/man/1/power/mechanical/gland_selector_shaft_getrag.html <&book>Сальник штока выбора передач GETRAG]]
****_ [[https://freelanderos.ru/man/1/power/mechanical/reversing_light_switch_getrag.html <&book>Выключатель фонарей заднего хода GETRAG]]
****_ [[https://freelanderos.ru/man/1/power/mechanical/contact_sensor_activate_first_gear_getrag.html <&book>Контактный датчик включения первой передачи GETRAG]]



*** Раздатка
****[#lightgreen] <&list> TAG000230 IRD Free 4 cyl
****[#lightgreen] <&list> TAG000220 IRD Free 6 cyl
**** Manual
*****_ [[https://www.freelanderos.ru/man/1/power/dropbox/changing_transmission_oil.html <&book>Замена трансмиссионного масла в раздаточной коробке: кроме стран Североамериканского рынка]]
*****_ [[https://www.freelanderos.ru/man/1/power/dropbox/changing_transmission_oil_north_american.html <&book>Замена трансмиссионного масла в раздаточной коробке: страны Североамериканского рынка]]
*****_ [[https://www.freelanderos.ru/man/1/power/dropbox/models_with_engine_td4.html <&book>Раздаточная коробка: модели с двигателем Td4]]
*****_ [[https://www.freelanderos.ru/man/1/power/dropbox/models_with_engine_k1_8.html <&book>Раздаточная коробка: модели с двигателем K1.8]]
*****_ [[https://www.freelanderos.ru/man/1/power/dropbox/models_with_engine_kv6.html <&book>Раздаточная коробка: модели с двигателем KV6]]
**** Сальники
*****_ [[https://www.freelanderos.ru/man/1/power/dropbox/oil_seal_drive_shaft_transfer_case.html <&book>Сальники ведущего вала раздаточной коробки]]
*****_ [[https://www.freelanderos.ru/man/1/power/dropbox/oil_seal_drive_shaft.html <&book>Сальник ведущего вала раздаточной коробки]]
*****_ [[https://www.freelanderos.ru/man/1/power/dropbox/gland_left_drive_shaft.html <&book>Сальниклевого приводного вала: модели с двигателем Td4 и KV6]]
*****_ [[https://www.freelanderos.ru/man/1/power/dropbox/gland_left_drive_shaft_k1_8.html <&book>Сальниклевого приводного вала: автомобили с двигателем K1.8]]
*****_ [[https://www.freelanderos.ru/man/1/power/dropbox/gland_right_drive_shaft.html <&book>Сальник правого приводного вала]]
*****_ [[https://www.freelanderos.ru/man/1/power/dropbox/oil_seal_rear_axle_drive_shaft_td4.html <&book>Сальник вала привода заднего моста: автомобили с двигателем Td4]]
*****_ [[https://www.freelanderos.ru/man/1/power/dropbox/oil_seal_rear_axle_drive_shaft_k1_8.html <&book>Сальник вала привода заднего моста: автомобили с двигателем K1.8]]
*****_ [[https://www.freelanderos.ru/man/1/power/dropbox/oil_seal_rear_axle_drive_shaft_kv6.html <&book>Сальник вала привода заднего моста KV6, кроме стран Североамериканского рынка]]
*****_ [[https://www.freelanderos.ru/man/1/power/dropbox/oil_seal_rear_axle_drive_shaft_kv6_north_american.html <&book>Сальник вала привода заднего моста KV6, для стран Североамериканского рынка]]
*****_ [[http://freelander.spybb.ru/viewtopic.php?id=1712 <&people>Форум: Сальники раздатки]]
*****_ [[http://freelander.spybb.ru/viewtopic.php?id=383#p12379 <&person>Подборка аналогов сальников, коды и размерность]]
*****_ [[https://freelanderos.ru/tech/sal.png <&image>Cхема иномера сальников]]
*****_ [[https://freelanderos.ru/tech/sal2.jpg <&image>Cхема2 иномера сальников]]
*****_ [[https://freelanderos.ru/tech/sal3.jpg <&image>Cхема3 иномера сальников]]
**** Подшипники
*****_ [[http://freelander.spybb.ru/viewtopic.php?id=383#p12792 <&person>KVK:Подборка кодов оригинальных подшипников]]
*****_ [[https://freelanderos.ru/tech/pod.jpg <&image>Схема и номера подшипников]]
**** Задняя крышка картера
*****_ [[https://www.freelanderos.ru/man/1/power/dropbox/laying_back_cover_transfer_case_td4.html <&book>Прокладка задней крышки картера раздаточной коробки: модели с двигателем Td4]]
*****_ [[https://www.freelanderos.ru/man/1/power/dropbox/laying_back_cover_transfer_case_kv6.html <&book>Прокладка задней крышки картера раздаточной коробки: модели с двигателем KV6]]
*****_ [[https://www.freelanderos.ru/man/1/power/dropbox/laying_back_cover_transfer_case_k1.8.html <&book>Прокладка задней крышки картера раздаточной коробки: модели с двигателем K1.8","https]]
**** Хвостовик
**** Ведущий вал
**** Приводной вал
**** Привод заднего моста
**** Масло
*****[#lightgreen] <&list> TEXACO S75w90
*****_ [[https://lrfreelander.ru/viewtopic.php?id=7353 <&people>Какое масло залить в раздатку]]
*****_ [[https://lrfreelander.ru/viewtopic.php?id=8475 <&people>Течь масла]]
**** Пробка заливного отверстия
*****[#lightgreen] <&list> trl100060
*****_ [[https://lrfreelander.ru/viewtopic.php?id=875 <&people>Пробка заливного отверстия (как открутить)]]
**** Радиатор
*****[#lightgreen] <&list> TAR100010 (4 цилиндра)
*****[#lightgreen] <&list> 8510256 (V6 K series)
*****_ [[http://freelander.spybb.ru/viewtopic.php?id=383&p=8#p60329 <&person>TOY:Совет: способ демонтажа радиатора (нагрев феном)]]
*****_ [[http://freelander.spybb.ru/viewtopic.php?id=383&p=12#p94304 <&person>Фотоотчет: способ демонтажа радиатора (нагрев жидкостью)]]
*****_ [[http://lrfreelander.ru/viewtopic.php?id=4092&p=4#p115086 <&person>Совет: способ демонтажа радиатора (компрессор+фуфайка)]]
**** Ремкомплект раздатки 
*****[#lightgreen] <&list> TAG000230KIT
***** Шайбы дифференциала
******[#lightgreen] <&list> IRD0011
*****_ [[https://lrfreelander.ru/viewtopic.php?id=341 <&people>Форум: Наборы для ремонта раздатки и редуктора]]
****_ [[https://freelanderos.ru/tech/ird.jpg <&image>Cхема: раздатки]]
*****[#lightgreen] <&list> 5: TRX100170
*****[#lightgreen] <&list> 7: TYX100490
*****[#lightgreen] <&list> 8: UNG100060L
*****[#lightgreen] <&list> 38: KOYO 32008JR
******_ Размеры 40.987х67.975х17.5
******_ Диаметр посадочного места 41,05мм
******[#lightgreen] <&list> Timken LM300849/811
******[#lightgreen] <&list> NSK LM 300849 RG3/811RG
*****[#lightgreen] <&list> 40: KOYO LM300849\11
******_ Размеры 40,000х68,000х19,000
******_ Диаметр посадочного места 40,03 мм.
******[#lightgreen] <&list> Timken 32008 XM (XAA32008X)
******[#lightgreen] <&list> NSK HR32008 XJ
*****_ [[https://freelanderos.ru/tech/pod.jpg <&image>Схема и номера подшипников]]
****_ [[https://lrfreelander.ru/viewtopic.php?id=383 <&people>Форум: Разборка и ремонт раздатки]]
*****_ [[http://freelander.spybb.ru/viewtopic.php?id=383&p=3#p27283 <&video>Видео: сборка раздатки]]
*****_ [[http://freelander.spybb.ru/viewtopic.php?id=383&p=12#p92052 <&video>Видео: снятие раздатки]]
*****_ [[http://freelander.spybb.ru/viewtopic.php?id=4092#p106288 <&person>Номера шайб больших и малых сателит]]
****_ [[https://lrfreelander.ru/viewtopic.php?id=7 <&people>Форум: Раздатка(IRD), карданы, вискомуфта]]
****_ [[http://freelander.spybb.ru/viewtopic.php?id=4261 <&info>Возможно ли сделать раздатку с понижающим рядом]] 
*****_ Невозможно в принципе
*** Сцепление
****_ [[https://freelanderos.ru/man/1/power/clutch/clutch_assembly_disc_td4.html <&book>Сцепление в сборе/ведомый диск и подшипник выключения сцепления (выжимной) - Td4]]
****_ [[https://freelanderos.ru/man/1/power/clutch/clutch_assembly_disc_k1_8.html <&book>Сцепление в сборе/ведомый диск и подшипник выключения сцепления (выжимной) - K1.8]]
**** Ведомый диск
**** Выжимной подшипник
**** Гидропривод
*****_ [[https://freelanderos.ru/man/1/power/clutch/hydraulic_clutch_hand_drive_cars_k1_8.html <&book>Гидравлический привод сцепления: автомобили с правосторонним управлением - K1.8]]
*****_ [[https://freelanderos.ru/man/1/power/clutch/master_cylinder_left_hand_drive_cars_td4.html <&book>Главный цилиндр: автомобили с левосторонним управлением - Td4]]
*****_ [[https://freelanderos.ru/man/1/power/clutch/master_cylinder_hand_drive_car_td4.html <&book>Главный цилиндр: автомобили с правосторонним управлением -Td4]]

*** Карданный вал
****_ [[https://freelanderos.ru/man/1/chassis/shafts/cardan_shaft_assembly.html <&book>Карданный вал в сборе]]
****_ [[https://freelanderos.ru/man/1/chassis/shafts/bulkhead_front_and_rear_driveshafts.html <&book>Переборка переднего и заднего карданных валов]]
**** Передний кардан
*****_ [[https://freelanderos.ru/man/1/chassis/shafts/cardan_shaft_front.html <&book>Карданный вал передний]]
*****_ [[https://freelanderos.ru/man/1/chassis/shafts/cover_the_sliding_yoke_front_cardan_shaft.html <&book>Чехол скользящей вилки карданного шарнира переднего карданного вала]]
**** Задний кардан
*****_ [[https://freelanderos.ru/man/1/chassis/shafts/cardan_shaft_rear.html <&book>Карданный вал задний]]
**** Вискомуфта
*****_ [[https://freelanderos.ru/man/1/chassis/shafts/viscous_clutch_assembly.html <&book>Вязкостная муфта в сборе]]
*****_ [[https://freelanderos.ru/man/1/chassis/shafts/intermediate_support_front.html <&book>Промежуточная опора передняя]]
***** [[https://lrfreelander.ru/viewtopic.php?id=7#p1365 <&people>Совет: способ проверки вискомуфты (вывешивсание и прокрутка)]]
***** [[https://lrfreelander.ru/viewtopic.php?id=7&p=3#p15526 <&people>Совет: способ проверки вискомуфты (троганье задним ходом с вывернутыми колесами)]]
***[#FF4C5B] <&warning*2>
****_ <&bug>Треск и щелчки при движении задним ходом с вывернутыми колесами
*****_ Неисправность раздатки, возможно заклинина вискомуфта
****_ [[https://lrfreelander.ru/viewtopic.php?id=8475 <&bug>Работает только задний привод]]
****_ [[https://lrfreelander.ru/viewtopic.php?id=826 <&bug>Давит масло из раздатки]]
****_ [[https://lrfreelander.ru/viewtopic.php?id=7696 <&bug>Удары при трогании с места]]
****_ [[https://lrfreelander.ru/viewtopic.php?id=4520 <&bug>Стук и удар по кузову при резком старте]]




** Выпускная система
** Система охлаждения и вентиляции


** Шасси
*** Рулевое управление
**** Рулевое колесо
*****_ [[https://freelanderos.ru/man/1/chassis/steering/steering_wheel.html <&book>Рулевое колесо - снятие и установка]]
**** Рулевая колонка
*****_ [[https://freelanderos.ru/man/1/chassis/steering/steering_column_assembly.html <&book>Рулевая колонка в сборе - внутренняя и наружная части]]
*****_ [[https://freelanderos.ru/man/1/chassis/steering/column_cover.html <&book>Кожух рулевой колонки]]
*****_ [[https://freelanderos.ru/man/1/chassis/steering/mechanism_locks_steering_wheel.html <&book>Механизм блокировки рулевого колеса и замок зажигания]]
******_ [[https://freelanderos.ru/man/1/chassis/steering/cable_lock_ignition.html <&book>Трос блокировки замка зажигания]]
*******_ [[https://freelanderos.ru/man/1/chassis/steering/adjustment_of_cable_locking_mechanism_ignition.html <&book>Регулировка троса механизма блокировки замка зажигания]]
**** Рулевой механизм
*****_ [[https://freelanderos.ru/man/1/chassis/steering/mechanism.html <&book>Рулевой механизм - снятие и установка]]
******_ [[https://freelanderos.ru/man/1/chassis/steering/protective_case_steering.html <&book>Защитный чехол рулевого механизма]]
*****_ [[https://freelanderos.ru/man/1/chassis/steering/spherical_rod_end.html <&book>Шаровой шарнир наконечника рулевой тяги]]
*****_ [[https://freelanderos.ru/man/1/chassis/steering/tie_rod.html <&book>Рулевая тяга - снятие и установка]]
*****_ [[https://freelanderos.ru/man/1/chassis/steering/adjustment_of_corners_of_forward_wheels.html <&book>Проверка и регулировка углов установки передних колес]]
*****_ [[https://freelanderos.ru/man/1/chassis/steering/adjustment_of_corners_of_back_wheels.html <&book>Проверка и регулировка углов установки задних колес]]

**** Гидроусилитель
*****_ [[https://freelanderos.ru/man/1/chassis/steering/check_pressure_in_hydraulic_booster.html <&book>Проверка давления в системе рулевого гидроусилителя]]
*****_ [[https://freelanderos.ru/man/1/chassis/steering/cooler_working_fluid_of_hydraulic_booster_td4.html <&book>Охладитель рабочей жидкости рулевого гидроусилителя (Td4 или K1.8)]]
*****_ [[https://freelanderos.ru/man/1/chassis/steering/cooler_working_fluid_of_hydraulic_booster_kv6.html <&book>Охладитель рабочей жидкости рулевого гидроусилителя (KV6)]]
*****_ [[https://freelanderos.ru/man/1/chassis/steering/drive_belt_k1_8.html <&book>Приводной ремень (для моделей с двигателем K1.8)]]
*****_ [[https://freelanderos.ru/man/1/chassis/steering/pumps_hydraulic_booster_kv6.html <&book>Насос рулевого гидроусилителя (модели с двигателем KV6)]]
*****_ [[https://freelanderos.ru/man/1/chassis/steering/pumps_hydraulic_booster_k1_8.html <&book>Насос рулевого гидроусилителя (модели с двигателем K1.8)]]
*****_ [[https://freelanderos.ru/man/1/chassis/steering/pumps_hydraulic_booster_td4.html <&book>Насос рулевого гидроусилителя (модели с двигателем Td4)]]
*** Приводные валы
**** Передние приводные валы
*****_ [[https://freelanderos.ru/man/1/chassis/shafts/left_shaft_with_external_and_internal_hinges.html <&book>Левый вал с внешним и внутренним шарнирами]]
*****_ [[https://freelanderos.ru/man/1/chassis/shafts/right_shaft_with_external_and_internal_hinges.html <&book>Правый вал с внешним и внутренним шарнирами]]
*****_ [[https://freelanderos.ru/man/1/chassis/shafts/protective_case_outside_front.html <&book>Защитный чехол - шарнир равных угловых скоростей - наружный - передний]]
*****_ [[https://freelanderos.ru/man/1/chassis/shafts/protective_case_outside_left_front.html <&book>Защитный чехол - шарнир равных угловых скоростей - наружный - левый - передний]]
*****_ [[https://freelanderos.ru/man/1/chassis/shafts/protective_case_internal_cv_joint.html <&book>Защитный чехол - внутренний шарнир равных угловых скоростей]]
**** Задние приводные валы
*****_ [[https://freelanderos.ru/man/1/chassis/shafts/rear_shaft_with_external_and_internal_hinges.html <&book>Задний вал с внешним и внутренним шарнирами]]
*****_ [[https://freelanderos.ru/man/1/chassis/shafts/cv_joint_outside_rear.html <&book>Шарнир равных угловых скоростей - наружный - задний]]
******_ [[https://freelanderos.ru/man/1/chassis/shafts/protective_case_outer_rear_hinge.html <&book>Защитный чехол наружного заднего шарнира]]
*****_ [[https://freelanderos.ru/man/1/chassis/shafts/protective_case_inner_cv_joint_rear.html <&book>Защитный чехол - внутренний шарнир равных угловых скоростей - задний]]


*** Задний мост и главная передача
****_ [[https://freelanderos.ru/man/1/chassis/rear_axle/differential_assembly.html <&book>Дифференциал в сборе]]
****_ [[https://freelanderos.ru/man/1/chassis/rear_axle/back_cover_of_differential.html <&book>Задняя крышка дифференциала]]
****_ [[https://freelanderos.ru/man/1/chassis/rear_axle/bushing_front_support_differential_housing.html <&book>Втулка передней опоры картера дифференциала]]
****_ [[https://freelanderos.ru/man/1/chassis/rear_axle/bushing_rear_support_differential_housing.html <&book>Втулка задней опоры картера дифференциала]]
****_ [[https://freelanderos.ru/man/1/chassis/rear_axle/oil_seal_drive_shaft_final_drive.html <&book>Сальник ведущего вала главной передачи]]
****_ [[https://freelanderos.ru/man/1/chassis/rear_axle/gland_rear_drive_shaft.html <&book>Сальник заднего приводного вала]]
*** Передняя подвеска
**** Стабилизатор поперечной устойчивости
*****_ [[https://freelanderos.ru/man/1/chassis/front_suspension/rubber_pads_rod_stabilizer_bar.html <&book>Резиновые подушки штанги стабилизатора поперечной устойчивости]]
*****_ [[https://freelanderos.ru/man/1/chassis/front_suspension/stabilizer_bar.html <&book>Стабилизатор поперечной устойчивости]]
*****_ [[https://freelanderos.ru/man/1/chassis/front_suspension/stabilizer_bar_tie.html <&book>Стойки стабилизатора поперечной устойчивости]]
*****_ [[https://freelanderos.ru/man/1/chassis/front_suspension/rubber_pads_rod_stabilizer_bar.html <&book>Резиновые подушки штанги стабилизатора поперечной устойчивости]]
**** Подшипник ступицы
*****_ [[https://freelanderos.ru/man/1/chassis/front_suspension/bearing_of_hub.html <&book>Подшипник ступицы - снятие и установка]]
**** Амортизатор
*****_ [[https://freelanderos.ru/man/1/chassis/front_suspension/shock_absorber.html <&book>Амортизатор - снятие и установка]]
**** Нижний рычаг
*****_ [[https://freelanderos.ru/man/1/chassis/front_suspension/lower_lever_assembly.html <&book>Нижний рычаг в сборе - снятие и установка]]
*****_ [[https://freelanderos.ru/man/1/chassis/front_suspension/silent_blocks_front_lower_arms.html <&book>Передние сайлент-блоки нижних рычагов]]
*****_ [[https://freelanderos.ru/man/1/chassis/front_suspension/rear_silent_blocks_lower_arms.html <&book>Задние сайлент-блоки нижних рычагов]]
**** Передний подрамник
*****_ [[https://freelanderos.ru/man/1/chassis/front_suspension/front_subframe.html <&book>Передний подрамник - снятие и установка]]
*** Задняя подвеска
**** Подшипники ступицы
*****_ [[https://freelanderos.ru/man/1/chassis/rear_suspension/bearing_of_hub.html <&book>Подшипник ступицы - снятие и установка]]
**** Амортизаторы
*****_ [[https://freelanderos.ru/man/1/chassis/rear_suspension/shock_absorber.html <&book>Амортизатор - снятие и установка]]
**** Продольный рычаг
*****_ [[https://freelanderos.ru/man/1/chassis/rear_suspension/trailing_arm.html <&book>Продольный рычаг - снятие и установка]]
*****_ [[https://freelanderos.ru/man/1/chassis/rear_suspension/silent_block_longitudinal_arm.html <&book>Сайлент-блок продольного рычага]]
*****_ [[https://freelanderos.ru/man/1/chassis/rear_suspension/silent_block_trailing_arm.html <&book>Сайлент-блок продольного рычага]]
**** Поперечные рычаги
*****_ [[https://freelanderos.ru/man/1/chassis/rear_suspension/adjustable_wishbone.html <&book>Регулируемый поперечный рычаг]]
*****_ [[https://freelanderos.ru/man/1/chassis/rear_suspension/unregulated_wishbone.html <&book>Нерегулируемый поперечный рычаг]]
*****_ [[https://freelanderos.ru/man/1/chassis/rear_suspension/silent_blocks_wishbone.html <&book>Сайлент-блоки поперечных рычагов]]
**** Подрамник
*****_ [[https://freelanderos.ru/man/1/chassis/rear_suspension/rear_subframe.html <&book>Задний подрамник - снятие и установка]]


*** Тормозная система
****_ [[https://freelanderos.ru/man/1/chassis/brake/removal_of_air.html <&book>Удаление воздуха из тормозной системы]]
**** Передние тормоза
*****_ [[https://freelanderos.ru/man/1/chassis/brake/front_brake_disc.html <&book>Передний тормозной диск - снятие и установка]]
*****_ [[https://freelanderos.ru/man/1/chassis/brake/front_left_brake_line.html <&book>Передний левый тормозной шланг]]
***** Передние колодки
******_ [[https://freelanderos.ru/man/1/chassis/brake/front_brake_pads.html <&book>Передние тормозные колодки]]
**** Задние тормоза
*****_ [[https://freelanderos.ru/man/1/chassis/brake/rear_brake_drum.html <&book>Задний тормозной барабан - снятие и установка]]
*****_ [[https://freelanderos.ru/man/1/chassis/brake/rear_brake_line.html <&book>Задний тормозной шланг]]
***** Задние колодки
******_ [[https://freelanderos.ru/man/1/chassis/brake/rear_brake_pads.html <&book>Задние тормозные колодки]]
***** Cтояночный тормоз
******_ [[https://freelanderos.ru/man/1/chassis/brake/check_and_adjust_parking_brake_cable.html <&book>Проверка и регулировка троса стояночной тормозной системы]]
******_ [[https://freelanderos.ru/man/1/chassis/brake/parking_brake_lever_assembly.html <&book>Рычаг стояночного тормоза в сборе]]
******_ [[https://freelanderos.ru/man/1/chassis/brake/parking_brake_cables.html <&book>Трос привода стояночного тормоза]]
******_ [[https://freelanderos.ru/man/1/chassis/brake/switch_off_alarm_brake.html <&book>Выключатель сигнализатора выключения стояночного тормоза]]
**** Главный цилиндр
*****_ [[https://freelanderos.ru/man/1/chassis/brake/dual_brake_master_cylinder_left.html <&book>Сдвоенный главный тормозной цилиндр - с левым рулевым колесом]]
*****_ [[https://freelanderos.ru/man/1/chassis/brake/dual_brake_master_cylinder_right.html <&book>Сдвоенный главный тормозной цилиндр - с правым рулевым колесом]]
**** Вакуумный усилитель
*****_ [[https://freelanderos.ru/man/1/chassis/brake/servo_assembly_left.html <&book>Вакуумный усилитель в сборе - с левым рулевым колесом]]
*****_ [[https://freelanderos.ru/man/1/chassis/brake/servo_assembly_right.html <&book>Вакуумный усилитель в сборе - с правым рулевым колесом]]
*****_ [[https://freelanderos.ru/man/1/chassis/brake/vacuum_pump_td4_and_manual.html <&book>Вакуумный насос - для автомобилей с двигателем Td4 и МКП]]
*****_ [[https://freelanderos.ru/man/1/chassis/brake/vacuum_pump_td4_and_automatic.html <&book>Вакуумный насос - для автомобилей с двигателем Td4 и АКП]]
*****_ [[https://freelanderos.ru/man/1/chassis/brake/power_vacuum_kv6.html <&book>Усилитель разрежения - для автомобилей с двигателем KV6]]
**** Педаль тормоза
*****_ [[https://freelanderos.ru/man/1/chassis/brake/brake_light_switch.html <&book>Выключатель стоп-сигналов]]



** Кузов
*** Информация
****[#yellow] <&info>VIN Номер
*****_ [[https://lrservice.info/obzory-land-rover/rasshifrovka-vin-land-rover/ <&info>Расшифровка VIN]]
*****_ [[https://freelanderos.ru/man/1/main/use/vehicle_identification_number.html <&book>Идентификационный номер автомобиля Расположение, расшифровка]]
'
**** Геометрия кузова
*****_ [[https://freelanderos.ru/man/1/carcass/geometry/information_on_size_of_control.html <&book>Информация о контрольных размерах]]
*****_ [[https://freelanderos.ru/man/1/carcass/geometry/point_of_front_end.html <&book>Характерные точки передней части кузова]]
*****_ [[https://freelanderos.ru/man/1/carcass/geometry/points_underbody.html <&book>Характерные точки днища кузова]]
*****_ [[https://freelanderos.ru/man/1/carcass/geometry/distances_between_points_of_front.html <&book>Расстояния между характерными точками передней части кузова]]
*****_ [[https://freelanderos.ru/man/1/carcass/geometry/points_front_and_side_parts_of_body.html <&book>Расстояние между точками передней и боковой частей кузова]]
*****_ [[https://freelanderos.ru/man/1/carcass/geometry/distances_between_points_of_rear.html <&book>Расстояния между характерными точками задней части кузова]]
*****_ [[https://freelanderos.ru/man/1/carcass/geometry/points_of_body_side.html <&book>Расстояние между характерными точками боковины кузова]]
*****_ [[https://freelanderos.ru/man/1/carcass/geometry/points_back_of_underbody.html <&book>Расстояния между точками задней части днища кузова]]
*****_ [[https://freelanderos.ru/man/1/carcass/geometry/size_of_gaps_and_profiles.html <&book>Размеры зазоров и профилей]]
**** Герметизация и антикор
*****_ [[https://freelanderos.ru/man/1/carcass/sealing/covering_hollow_protective_wax_3.html <&book>Покрытие скрытых полостей защитным воском и отверстия - 3-дверный кузов]]
*****_ [[https://freelanderos.ru/man/1/carcass/sealing/holes_for_cavity_protection_threshold_5.html <&book>Отверстия для защиты внутренней полости порога - 5-дверный кузов]]
*****_ [[https://freelanderos.ru/man/1/carcass/sealing/covering_hollow_protective_wax_5.html <&book>Покрытие скрытых полостей защитным воском и отверстия - 5-дверный кузов]]
*****_ [[https://freelanderos.ru/man/1/carcass/sealing/places_underbody.html <&book>Места днища кузова, обрабатываемые герметизирующими материалами]]
*****_ [[https://freelanderos.ru/man/1/carcass/sealing/adhesive_materials_for_bearing_elements.html <&book>Адгезионные материалы для несущих элементов кузова]]
*****_ [[https://freelanderos.ru/man/1/carcass/sealing/materials_for_sealing_joints.html <&book>Материалы для герметизации швов]]
*****_ [[https://freelanderos.ru/man/1/carcass/sealing/acoustic_insulation_foaming_material.html <&book>Акустическая изоляция вспенивающимся материалом]]
*****_ [[https://freelanderos.ru/man/1/carcass/repair/replacement_body_parts.html <&book>Заменяемые кузовные детали]]
*** Передняя часть
**** Капот
*****_ [[https://freelanderos.ru/man/1/carcass/external/hood.html <&book>Капот - снятие и установка]]
***** Трос капота
******_ [[https://freelanderos.ru/man/1/carcass/external/cable_release_bonnet.html <&book>Трос/тяга разблокировки замка капота]]
***** Замок капота
****** Панель замка капота
*******_ [[https://freelanderos.ru/man/1/carcass/repair/panel_bonnet.html <&book>Панель замка капота]]
****_ [[https://freelanderos.ru/man/1/carcass/repair/panel_front_end_assembly.html <&book>Панель передка в сборе]]
****_ [[https://freelanderos.ru/man/1/carcass/repair/mounting_bracket_lights.html <&book>Кронштейн крепления фары]]
****_ [[https://freelanderos.ru/man/1/carcass/repair/front_cross_member.html <&book>Передняя поперечина, нижняя]]
****_ [[https://freelanderos.ru/man/1/carcass/repair/front_side_member_assembly.html <&book>Передний лонжерон в сборе]]
****_ [[https://freelanderos.ru/man/1/carcass/repair/front_side_member.html <&book>Передний лонжерон (передняя часть)]]
****_ [[https://freelanderos.ru/man/1/carcass/repair/sidewall_engine_compartment_assembly.html <&book>Боковина моторного отсека в сборе]]
****_ [[https://freelanderos.ru/man/1/carcass/repair/upper_side_engine_compartment.html <&book>Верхняя боковина моторного отсека]]
****_ [[https://freelanderos.ru/man/1/carcass/repair/front_side_panel_engine_compartment.html <&book>Передняя панель боковины моторного отсека]]
****_ [[https://freelanderos.ru/man/1/carcass/repair/strengthening_outer_panel_wheel_arch.html <&book>Усиление наружной панели колесной арки]]
****_ [[https://freelanderos.ru/man/1/carcass/repair/a_rack_of_body_3.html <&book>Стойка А кузова - 3-дверная версия]]
****_ [[https://freelanderos.ru/man/1/carcass/repair/a_rack_of_body_5.html <&book>Стойка А кузова - 5-дверная версия]]
****_ [[https://freelanderos.ru/man/1/carcass/repair/power_threshold_3.html <&book>Усилитель порога - 3-дверная версия]]
****_ [[https://freelanderos.ru/man/1/carcass/repair/power_threshold_5.html <&book>Усилитель порога - 5-дверная версия]]
****_ [[https://freelanderos.ru/man/1/carcass/repair/panel_strengthen_central_pillar_bc_3.html <&book>Панель усиления центральной стойки В/С - 3-дверная версия]]
****_ [[https://freelanderos.ru/man/1/carcass/repair/panel_strengthen_central_pillar_bc_5.html <&book>Панель усиления центральной стойки В/С- 5-дверная версия]]

*** Боковины
**** Двери
*****_ [[https://freelanderos.ru/man/1/carcass/doors/removing_front_door_assembly.html <&book>Демонтаж передней двери в сборе для обеспечения доступа к другим элементам]]
*****_ [[https://freelanderos.ru/man/1/carcass/doors/removing_rear_door_assembly.html <&book>Демонтаж задней двери в сборе для обеспечения доступа к другим элементам]]
*****_ [[https://freelanderos.ru/man/1/carcass/doors/removing_tailgate_assembly.html <&book>Демонтаж двери багажного отделения в сборе для обеспечения доступа к другим элементам]]

***** Накладки дверей
****** 3х дверка
*******_ [[https://freelanderos.ru/man/1/carcass/doors/lower_plastic_overlay_front_door_3.html <&book>Нижняя пластиковая накладка передней двери 3-дверного автомобиля]]
*******_ [[https://freelanderos.ru/man/1/carcass/doors/pocket_front_door_3.html <&book>Карман передней двери 3-дверного автомобиля]]
*******_ [[https://freelanderos.ru/man/1/carcass/doors/top_plastic_overlay_front_door_3.html <&book>Верхняя пластиковая накладка передней двери 3-дверного автомобиля]]
*******_ [[https://freelanderos.ru/man/1/carcass/doors/decorative_panel_of_front_door_3.html <&book>Декоративная панель передней двери 3-дверного автомобиля]]
****** 5и дверка
******* Передние
********_ [[https://freelanderos.ru/man/1/carcass/doors/plastic_lining_of_front_door_5.html <&book>Пластиковая накладка передней двери 5-дверного автомобиля]]
********_ [[https://freelanderos.ru/man/1/carcass/doors/decorative_panel_front_door_5.html <&book>Декоративная панель передней двери 5-дверного автомобиля - до 2004-го года]]
********_ [[https://freelanderos.ru/man/1/carcass/doors/decorative_panel_front_door_5_after_2004.html <&book>Декоративная панель передней двери 5-дверного автомобиля - после 2004-го года]]
******* Задние
********_ [[https://freelanderos.ru/man/1/carcass/doors/decorative_panel_tailgate_after_2004.html <&book>Декоративная панель задней двери для автомобилей после 2004-го года]]
********_ [[https://freelanderos.ru/man/1/carcass/doors/plastic_pad_tailgate.html <&book>Пластиковая накладка задней двери]]
********_ [[https://freelanderos.ru/man/1/carcass/doors/decorative_panel_tailgate_before_2004.html <&book>Декоративная панель задней двери для автомобилей до 2004-го года]]
********_ [[https://freelanderos.ru/man/1/carcass/doors/decorative_panel_tailgate_after_2004.html <&book>Декоративная панель задней двери для автомобилей после 2004-го года]]

***** Замки дверей
******_ [[https://freelanderos.ru/man/1/carcass/doors/lock_front_door_3.html <&book>Замок передней двери 3-дверного автомобиля]]
******_ [[https://freelanderos.ru/man/1/carcass/doors/lock_front_door_5.html <&book>Замок передней двери 5-дверного автомобиля]]
******_ [[https://freelanderos.ru/man/1/carcass/doors/lock_back_door.html <&book>Замок задней двери]]
******_ [[https://freelanderos.ru/man/1/carcass/doors/lock_tailgate.html <&book>Замок двери багажного отделения]]
******_ [[https://freelanderos.ru/man/1/carcass/doors/adjusting_striker_front_or_rear_door.html <&book>Регулировка фиксатора замка передней или задней двери]]


***** Ручка внутренняя
******_ [[https://freelanderos.ru/man/1/carcass/doors/handle_unlocking_front_door.html <&book>Рукоятка отпирания замка передней двери]]
******_ [[https://freelanderos.ru/man/1/carcass/doors/handle_unlocking_back_door.html <&book>Рукоятка отпирания замка задней двери]]
******_ [[https://freelanderos.ru/man/1/carcass/doors/cable_grip_unlocking_door_lock_5.html <&book>Трос рукоятки отпирания дверного замка 5-дверного автомобиля]]
******_ [[https://freelanderos.ru/man/1/carcass/doors/inner_door_handle_5.html <&book>Внутренняя дверная ручка 5-дверного автомобиля - до 2004-го года]]

***** Ручка наружная
******_ [[https://freelanderos.ru/man/1/carcass/doors/external_handle_rear_door.html <&book>Наружная ручка задней двери]]
******_ [[https://freelanderos.ru/man/1/carcass/doors/external_handle_tailgate.html <&book>Наружная ручка двери багажного отделения]]
******_ [[https://freelanderos.ru/man/1/carcass/doors/external_handle_front_door.html <&book>Наружная ручка передней двери]]


***** Петли
******_ [[https://freelanderos.ru/man/1/carcass/doors/adjusting_front_door_hinges.html <&book>Регулировка петель передней двери]]

***** Стёкла
******_ [[https://freelanderos.ru/man/1/carcass/doors/glass_front_door.html <&book>Стекло передней двери]]
******_ [[https://freelanderos.ru/man/1/carcass/doors/glass_rear_door.html <&book>Стекло задней двери]]
******_ [[https://freelanderos.ru/man/1/carcass/doors/side_pad_rear_window_5.html <&book>Боковая накладка заднего стекла 5-дверного автомобиля]]
******_ [[https://freelanderos.ru/man/1/carcass/doors/side_pad_rear_window_5.html <&book>Боковая накладка заднего стекла 5-дверного автомобиля]]
******_ [[https://freelanderos.ru/man/1/carcass/doors/glass_tailgate.html <&book>Стекло двери багажного отделения]]
******_ [[https://freelanderos.ru/man/1/carcass/external/rear_small_window_assembly_3.html <&book>Заднее малое стекло в сборе - 3-дверный автомобиль]]
***** Уплотнители
******_ [[https://freelanderos.ru/man/1/carcass/doors/rubber_window_seals_front_door.html <&book>Резиновый/фетровый оконный уплотнитель передней двери]]
******_ [[https://freelanderos.ru/man/1/carcass/doors/rubber_window_seal_rear_door.html <&book>Резиновый/фетровый оконный уплотнитель задней двери]]
******_ [[https://freelanderos.ru/man/1/carcass/doors/inside_lower_window_seal_tailgate.html <&book>Внутренний нижний оконный уплотнитель двери багажного отделения]]
***** Стеклоподёмники
******_ См.Электрооборудование - Модули управления - Стеклоподёмники
***** Зеркала
******_ [[https://freelanderos.ru/man/1/carcass/external/door_mirrors_with_electric_adjustment.html <&book>Наружное зеркало заднего вида с электроприводом регулировки]]
****** Складывание зеркал
*******_ См.Электрооборудование - Модули управления - Складывание зеркал


**** Крылья
*****_ [[https://freelanderos.ru/man/1/carcass/external/front_wing.html <&book>Переднее крыло - снятие и установка]]
*****_ [[https://freelanderos.ru/man/1/carcass/external/front_wheel_arch_liner.html <&book>Передний подкрылок - снятие и установка]]
*****_ [[https://freelanderos.ru/man/1/carcass/external/rear_wheel_arch_liner.html <&book>Задний подкрылок - снятие и установка]]
*****_ [[https://freelanderos.ru/man/1/carcass/external/front_mudguard.html <&book>Передний брызговик - снятие и установка]]
*****_ [[https://freelanderos.ru/man/1/carcass/external/rear_mudguard.html <&book>Задний брызговик - снятие и установка]]
*****_ [[https://freelanderos.ru/man/1/carcass/external/back_of_rear_wheel_arch_extender.html <&book>Задняя часть расширителя задней колесной арки]]

*** Задняя часть
**** Дверь багажника
*****_ [[https://freelanderos.ru/man/1/carcass/doors/decorative_panel_tailgate.html <&book>Декоративная панель двери багажного отделения]]
*****_ [[https://freelanderos.ru/man/1/carcass/doors/plastic_pad_liftgate.html <&book>Пластиковая накладка двери багажного отделения]]
***** Кронштейн запаски
******_ [[https://freelanderos.ru/man/1/carcass/external/spare_wheel_mounting_bracket.html <&book>Кронштейн крепления запасного колеса]]


*** Крыша
****_ [[https://freelanderos.ru/man/1/carcass/external/roof_molding_5.html <&book>Молдинги крыши 5-дверного автомобиля]]
**** Багажник
***** 3х дверка
***** 5и дверка
******_ [[https://freelanderos.ru/man/1/carcass/external/side_rails_on_upper_tailgate_5.html <&book>Боковой рейлинг верхнего багажника 5-дверного автомобиля]]
**** Люк
***** 3х дверка
******_ [[https://freelanderos.ru/man/1/carcass/sunroof/vent_sunroof_3_door_vehicle.html <&book>Вентиляционный люк в крыше 3-дверного автомобиля]]
******_ [[https://freelanderos.ru/man/1/carcass/sunroof/deflector_sunroof_3.html <&book>Дефлектор люка в крыше 3-дверного автомобиля]]
******_ [[https://freelanderos.ru/man/1/carcass/sunroof/seal_sunroof.html <&book>Уплотнитель люка в крыше]]
***** 5и дверка
******_ [[https://freelanderos.ru/man/1/carcass/sunroof/vent_sunroof_5_door_vehicle.html <&book>Вентиляционный люк в крыше 5-дверного автомобиля]]
******_ [[https://freelanderos.ru/man/1/carcass/sunroof/glass_panel_ventilation_hatch_5.html <&book>Стеклянная панель вентиляционного люка в крыше 5-дверного автомобиля]]
******_ [[https://freelanderos.ru/man/1/carcass/sunroof/seal_glass_cover_ventilation_hatch_5.html <&book>Уплотнитель стеклянной крышки вентиляционного люка в крыше 5-дверного автомобиля]]
******_ [[https://freelanderos.ru/man/1/carcass/sunroof/gearmotor_electric_ventilation_hatch_5.html <&book>Моторедуктор электропривода вентиляционного люка в крыше 5-дверного автомобиля]]
******_ [[https://freelanderos.ru/man/1/carcass/sunroof/cables_and_drive_ventilation_hatch_5.html <&book>Тросы и привод вентиляционного люка 5-дверного автомобиля]]
******_ [[https://freelanderos.ru/man/1/carcass/sunroof/front_drainage_pipe_ventilation_hatch_5.html <&book>Передние водоотводные трубки вентиляционного люка в крыше 5-дверного автомобиля]]
******_ [[https://freelanderos.ru/man/1/carcass/sunroof/rear_drainage_pipe_ventilation_hatch_5.html <&book>Задние водоотводные трубки вентиляционного люка в крыше 5-дверного автомобиля]]
******_ [[https://freelanderos.ru/man/1/carcass/sunroof/internal_escutcheon.html <&book>Внутренняя декоративная накладка]]
******_ [[https://freelanderos.ru/man/1/carcass/sunroof/deflector_sunroof_5.html <&book>Дефлектор люка в крыше 5-дверного автомобиля]]
******_ [[https://freelanderos.ru/man/1/carcass/sunroof/curtain_ventilation_hatch_5.html <&book>Шторка вентиляционного люка 5-дверного автомобиля]]
******_ [[https://freelanderos.ru/man/1/carcass/sunroof/key_management_vent_sunroof.html <&book>Клавиша управления вентиляционным люком в крыше]]
******_ [[https://freelanderos.ru/man/1/carcass/sunroof/seal_trough_ventilation_hatch_5.html <&book>Уплотнитель желоба вентиляционного люка в крыше 5-дверного автомобиля]]
**** Съемная крыша 3х дверки
***** Жесткая крыша
******_ [[https://freelanderos.ru/man/1/carcass/roof/hardtop.html <&book>Жесткая крыша - снятие для доступа к месту ремонта и установка]]
******_ [[https://freelanderos.ru/man/1/carcass/roof/side_window_hardtop.html <&book>Боковое стекло жесткой крыши]]
******_ [[https://freelanderos.ru/man/1/carcass/roof/seal_hardtop.html <&book>Уплотнитель жесткой крыши]]
******_ [[https://freelanderos.ru/man/1/carcass/roof/front_latch_and_lock_hardtop.html <&book>Передние защелка и фиксатор жесткой крыши]]
******_ [[https://freelanderos.ru/man/1/carcass/roof/rear_latch_and_lock_hardtop.html <&book>Задние защелка и фиксатор жесткой крыши]]
***** Тент
******_ [[https://freelanderos.ru/man/1/carcass/roof/frame_and_awning_assembly.html <&book>Каркас и тент в сборе - снятие для доступа к месту ремонта и установка]]
******_ [[https://freelanderos.ru/man/1/carcass/roof/awning.html <&book>Тент - снятие и установка]]

*** Пассивная безопастность
**** Ремни безопастности
*****_ [[https://freelanderos.ru/man/1/carcass/passive_safety/height_adjustable_belt_loop_on_middle_b_pillar.html <&book>Регулируемая по высоте петля ремня безопасности на средней B стойке кузова]]
***** Замки ремней безопастности
******_ [[https://freelanderos.ru/man/1/carcass/passive_safety/belt_buckle_left_rear_seats_3.html <&book>Замок ремня безопасности левого места на заднем сиденье 3-дверного автомобиля]]
******_ [[https://freelanderos.ru/man/1/carcass/passive_safety/belt_buckle_left_rear_seats_5.html <&book>Замок ремня безопасности левого места на заднем сиденье 5-дверного автомобиля]]
*****_ [[https://freelanderos.ru/man/1/carcass/passive_safety/belt_buckle_central_place_back_seat.html <&book>Замок ремня безопасности центрального места на заднем сиденье]]
***** Преднатяжители
******_ [[https://freelanderos.ru/man/1/carcass/passive_safety/pretensioner_front_seat_belt.html <&book>Преднатяжитель переднего ремня безопасности]]
*****_ [[https://freelanderos.ru/man/1/carcass/passive_safety/triggering_dismantled_pretensioner_front_seat_belt.html <&book>Срабатывание демонтированного преднатяжителя переднего ремня безопасности]]
*****_ [[https://freelanderos.ru/man/1/carcass/passive_safety/triggering_pretensioner_front_seat_belt_without_dismantle.html <&book>Срабатывание преднатяжителя переднего ремня безопасности без демонтажа с автомобиля]]
**** Подушки безопастности
*****_ [[https://freelanderos.ru/man/1/carcass/passive_safety/rotary_contactor_airbag_system.html <&book>Поворотный контактор системы подушек безопасности]]
***** Подушка водителя
******_ [[https://freelanderos.ru/man/1/carcass/passive_safety/driver_airbag.html <&book>Подушка безопасности водителя]]
******_ [[https://freelanderos.ru/man/1/carcass/passive_safety/rotary_contactor_airbag_system.html <&book>Поворотный контактор системы подушек безопасности]]
******_ [[https://freelanderos.ru/man/1/carcass/passive_safety/triggering_dismantled_from_car_driver_airbag.html <&book>Срабатывание демонтированной с автомобиля подушки безопасности водителя]]
******_ [[https://freelanderos.ru/man/1/carcass/passive_safety/driver_airbag_deployment_without_dismantle_from_car.html <&book>Срабатывание подушки безопасности водителя без демонтажа с автомобиля]]
***** Подушка пассажира
******_ [[https://freelanderos.ru/man/1/carcass/passive_safety/front_passenger_airbag_before_2004.html <&book>Подушка безопасности переднего пассажира - до 2004 модельного года]]
******_ [[https://freelanderos.ru/man/1/carcass/passive_safety/front_passenger_airbag_after_2004.html <&book>Подушка безопасности переднего пассажира - после 2004-го года]]
******_ [[https://freelanderos.ru/man/1/carcass/passive_safety/triggering_dismantled_from_vehicle_airbags.html <&book>Срабатывание демонтированной с автомобиля подушки безопасности переднего пассажира]]
**** Блок SRS(DCU)
*****_ [[https://freelanderos.ru/man/1/carcass/passive_safety/dcu.html <&book>Блок бортовой диагностики SRS(DCU)]]

*** Дополнительное оборудование
**** Бампера
***** Передний бампер
******_ [[https://freelanderos.ru/man/1/carcass/external/front_bumper_assembly_before_2004.html <&book>Передний бампер в сборе - для автомобилей до 2004-го года]]
******_ [[https://freelanderos.ru/man/1/carcass/external/front_bumper_assembly_after_2004.html <&book>Передний бампер в сборе - для автомобилей после 2004-го года]]
***** Задний бампер
******_ [[https://freelanderos.ru/man/1/carcass/external/rear_bumper_assembly_before_2004.html <&book>Задний бампер в сборе - для автомобилей до 2004-го года]]
******_ [[https://freelanderos.ru/man/1/carcass/external/rear_bumper_assembly_after_2004.html <&book>Задний бампер в сборе - для автомобилей после 2004-го года]]
**** Защита двигателя
*****_ [[https://freelanderos.ru/man/1/carcass/external/lower_shield_engine_protection.html <&book>Нижний щит защиты двигателя]]
**** Пороги
*****_ [[https://freelanderos.ru/man/1/carcass/external/scuff_plates.html <&book>Накладка порога - снятие и установка]]



** Салон
*** Потолок
****_ [[https://freelanderos.ru/man/1/carcass/interior/ceiling_panel_3.html <&book>Потолочная панель 3-дверного автомобиля]]
**** Солнцезащитные козырьки
*****_ [[https://freelanderos.ru/man/1/carcass/interior/sun_visor.html <&book>Солнцезащитный козырек - снятие и установка]]
*** Стойки
****_ [[https://freelanderos.ru/man/1/carcass/interior/top_decorative_panel_a_pillar.html <&book>Замена верхней декоративной панели передней стойки A]]
****_ [[https://freelanderos.ru/man/1/carcass/interior/top_decorative_panel_rack_b_c.html <&book>Замена верхней декоративной панели стойки B/C]]
****_ [[https://freelanderos.ru/man/1/carcass/interior/bottom_decorative_panel_pillar_b_5.html <&book>Нижняя декоративная панель средней стойки B 5-дверного автомобиля]]
*** Багажник
**** 3х дверка
*****_ [[https://freelanderos.ru/man/1/carcass/interior/bottom_decorative_panel_trunk_3.html <&book>Нижняя декоративная панель багажного отделения 3-дверного автомобиля]]
*****_ [[https://freelanderos.ru/man/1/carcass/interior/upper_decorative_panel_trunk_3.html <&book>Верхняя декоративная панель багажного отделения 3-дверного автомобиля]]
**** 5и дверка
*****_ [[https://freelanderos.ru/man/1/carcass/interior/bottom_decorative_panel_trunk_5.html <&book>Нижняя декоративная панель багажного отделения 5-дверного автомобиля]]
*****_ [[https://freelanderos.ru/man/1/carcass/interior/upper_decorative_panel_trunk_5.html <&book>Верхняя декоративная панель багажного отделения 5-дверного автомобиля]]
*** Передняя консоль
****_ [[https://freelanderos.ru/man/1/carcass/interior/center_console_before_2004.html <&book>Центральная консоль - для автомобилей до 2004-го года]]
****_ [[https://freelanderos.ru/man/1/carcass/interior/front_console_assembly_after_2004.html <&book>Передняя консоль в сборе - для автомобилей после 2004-го года]]
****_ [[https://freelanderos.ru/man/1/carcass/interior/control_panel_before_2004.html <&book>Панель управления - для автомобилей до 2004-го модельного года]]
****_ [[https://freelanderos.ru/man/1/carcass/interior/control_panel_after_2004.html <&book>Панель управления - для автомобилей после 2004-го года]]
*** Подлокотник
****_ [[https://freelanderos.ru/man/1/carcass/interior/rear_console.html <&book>Задняя консоль - снятие и установка]]
*** Торпедо
**** Подстаканник
*****_ [[https://freelanderos.ru/man/1/carcass/interior/holder_on_control_panel_after_2004.html <&book>Подстаканник на панели управления - после 2004-го года]]
*****_ [[https://freelanderos.ru/man/1/carcass/interior/control_panel_holder_before_2004.html <&book>Подстаканник панели управления для автомобилей до 2004-го года]]
*****_ [[https://freelanderos.ru/man/1/carcass/interior/branch_control_panel.html <&book>Отделение панели управления]]
**** Бардачки
*****_ [[https://freelanderos.ru/man/1/carcass/interior/glovebox.html <&book>Перчаточный ящик - снятие и установка]]
*** Пол
****_ [[https://freelanderos.ru/man/1/carcass/interior/flooring_luggage.html <&book>Напольное покрытие багажного отделения]]
*** Боковая панель 3х дверки
****_ [[https://freelanderos.ru/man/1/carcass/interior/rear_side_decorative_panel_3.html <&book>Задняя боковая декоративная панель 3-дверного автомобиля]]
*** Сидения
**** Передние
*****_ [[https://freelanderos.ru/man/1/carcass/seats/front_seat.html <&book>Переднее сиденье - снятие и установка]]
*****_ [[https://freelanderos.ru/man/1/carcass/seats/upholstery_front_seat.html <&book>Обивка подушки переднего сиденья]]
*****_ [[https://freelanderos.ru/man/1/carcass/seats/roller_lumbar_support_on_front_seat.html <&book>Валик поясничного упора переднего сиденья с ручной регулировкой]]
*****_ [[https://freelanderos.ru/man/1/carcass/seats/lock_right_rear_seat_backrest.html <&book>Замок спинки заднего правого сиденья]]
*****_ [[https://freelanderos.ru/man/1/carcass/seats/lock_backrest_rear_left_seat.html <&book>Замок спинки заднего левого сиденья]]
*****_ [[https://freelanderos.ru/man/1/carcass/seats/upholstery_front_seatback.html <&book>Обивка спинки переднего сиденья]]
***** Накладки
******_ [[https://freelanderos.ru/man/1/carcass/seats/covers_bases_front_seats.html <&book>Накладки оснований передних сидений]]
******_ [[https://freelanderos.ru/man/1/carcass/seats/side_panel_front_seat.html <&book>Боковая накладка подушки переднего сиденья]]
**** Задние
***** Левое
******_ [[https://freelanderos.ru/man/1/carcass/seats/rear_left_seat.html <&book>Заднее левое сиденье - снятие и установка]]
******_ [[https://freelanderos.ru/man/1/carcass/seats/upholstery_rear_right_seat_cushion.html <&book>Обивка подушки заднего правого сиденья]]
******_ [[https://freelanderos.ru/man/1/carcass/seats/upholstery_backrest_rear_left_seat.html <&book>Обивка спинки заднего левого сиденья]]
***** Правое
******_ [[https://freelanderos.ru/man/1/carcass/seats/rear_right_seat.html <&book>Заднее правое сиденье - снятие и установка]]
******_ [[https://freelanderos.ru/man/1/carcass/seats/upholstery_rear_left_seat_cushion.html <&book>Обивка подушки заднего левого сиденья]]
******_ [[https://freelanderos.ru/man/1/carcass/seats/upholstery_right_rear_seat_backrest.html <&book>Обивка спинки заднего правого сиденья]]
***** Неразрезное 3х дверка
******_ [[https://freelanderos.ru/man/1/carcass/seats/cushion_and_back_of_continuous_seats_3.html <&book>Подушка и спинка заднего неразрезного сиденья 3-дверного автомобиля]]
******_ [[https://freelanderos.ru/man/1/carcass/seats/upholstery_cushion_rear_seats_uncut_3.html <&book>Обивка подушки заднего неразрезного сиденья 3-дверного автомобиля]]
******_ [[https://freelanderos.ru/man/1/carcass/seats/upholstery_seat_backrests_uncut_3.html <&book>Обивка спинки заднего неразрезного сиденья 3-дверного автомобиля]]

** Электрооборудование
*** Реле
*** Отопление и вентиляция
**** Отопитель
*****_ [[https://freelanderos.ru/man/1/electrics/heating/heater_controls_before_2004.html <&book>Панель управления отопителем - для автомобилей до 2004-го года]]
*****_ [[https://freelanderos.ru/man/1/electrics/heating/heater_controls_after_2004.html <&book>Панель управления отопителем - для автомобилей после 2004-го года]]
*****_ [[https://freelanderos.ru/man/1/electrics/heating/heater.html <&book>Отопитель - снятие и установка]]
*****_ [[https://freelanderos.ru/man/1/electrics/heating/heater_radiator.html <&book>Радиатор отопителя - снятие и установка]]
**** Вентилятор
*****_ [[https://freelanderos.ru/man/1/electrics/heating/fan_speed_controller.html <&book>Регулятор частоты вращения вентилятора]]
*****_ [[https://freelanderos.ru/man/1/electrics/heating/heater_fan_assembly.html <&book>Вентилятор отопителя в сборе]]
*****_ [[https://freelanderos.ru/man/1/electrics/heating/power_resistor.html <&book>Блок резистора - электродвигатель вентилятора]]
**** Подача воздуха
*****_ [[https://freelanderos.ru/man/1/electrics/heating/gearmotor_air_recirculation_in_cabin.html <&book>Моторедуктор режима рециркуляции воздуха в салоне]]
*****_ [[https://freelanderos.ru/man/1/electrics/heating/switch_recirculated_air_in_cabin.html <&book>Выключатель режима рециркуляции воздуха в салоне]]
*****_ [[https://freelanderos.ru/man/1/electrics/heating/left_deflector_panel.html <&book>Левый дефлектор панели управления]]
*****_ [[https://freelanderos.ru/man/1/electrics/heating/air_intake_duct.html <&book>Короб воздухозаборника - снятие и установка]]
**** Электрический подогреватель
*****_ [[https://freelanderos.ru/man/1/electrics/heating/heating_element_electric_heater_td4.html <&book>Нагревательный элемент электрического подогревателя - с двигателем Td4]]
*****_ [[https://freelanderos.ru/man/1/electrics/heating/cable_electric_heater_td4.html <&book>Кабель электрического подогревателя - с двигателем Td4]]
*****_ [[https://freelanderos.ru/man/1/electrics/heating/microswitch_electric_heater_td4.html <&book>Микровыключатель электрического подогревателя - с двигателем Td4]]
*****_ [[https://freelanderos.ru/man/1/electrics/heating/power_relay_electric_heater_td4.html <&book>Реле мощности электрического подогревателя - с двигателем Td4]]
*****_ [[https://freelanderos.ru/man/1/electrics/heating/control_relay_electric_heater_td4.html <&book>Управляющее реле электрического подогревателя - с двигателем Td4]]
**** Подогреватель на жидком топлеве
*****_ [[https://freelanderos.ru/man/1/electrics/heating/fbh.html <&book>Подогреватель на жидком топливе (FBH)]]
*****_ [[https://freelanderos.ru/man/1/electrics/heating/fuel_pump_heater_on_liquid_fuel_before_2003.html <&book>Топливный насос подогревателя на жидком топливе - до 2003-го года]]
*****_ [[https://freelanderos.ru/man/1/electrics/heating/fuel_pump_heater_on_liquid_fuel_after_2003.html <&book>Топливный насос подогревателя на жидком топливе - после 2003-го года]]
**** Датчики
*****_ [[https://freelanderos.ru/man/1/electrics/heating/outdoor_temperature_sensor.html <&book>Датчик температуры наружного воздуха (ОТ)]]
*** Кондиционер
****_ [[https://freelanderos.ru/man/1/electrics/conditioning/emptying_conditioner.html <&book>Опорожнение кондиционера - восстановление хладагента и заправка]]
****_ [[https://freelanderos.ru/man/1/electrics/conditioning/compressor_drive_belt_td4.html <&book>Ремень привода компрессора кондиционера - с двигателем Td4]]
****_ [[https://freelanderos.ru/man/1/electrics/conditioning/dehumidifier_receiver.html <&book>Влагоотделитель ресивера - снятие и установка]]
****_ [[https://freelanderos.ru/man/1/electrics/conditioning/air_conditioner_switch.html <&book>Выключатель кондиционера - снятие и установка]]
****_ [[https://freelanderos.ru/man/1/electrics/conditioning/coolant_pressure_sensor.html <&book>Датчик давления хладагента - снятие и установка]]
****_ [[https://freelanderos.ru/man/1/electrics/conditioning/txv.html <&book>Терморегулирующий вентиль (TXV)]]
**** Компрессор
*****_ [[https://freelanderos.ru/man/1/electrics/conditioning/conditioner_compressor_td4.html <&book>Компрессор кондиционера - для моделей с двигателем Td4]]
*****_ [[https://freelanderos.ru/man/1/electrics/conditioning/conditioner_compressor_kv6.html <&book>Компрессор кондиционера - для моделей с двигателем KV6]]
*****_ [[https://freelanderos.ru/man/1/electrics/conditioning/conditioner_compressor_k_1_8.html <&book>Компрессор кондиционера - для моделей с двигателем K1.8]]
**** Конденсатор
*****_ [[https://freelanderos.ru/man/1/electrics/conditioning/capacitor.html <&book>Конденсатор - снятие и установка]]
**** Испаритель
*****_ [[https://freelanderos.ru/man/1/electrics/conditioning/evaporator.html <&book>Испаритель - снятие и установка]]
*** Дворники
****_ [[https://freelanderos.ru/man/1/electrics/wipers/lever_one.html <&book>Рычаг - стеклоочиститель - одна]]
****_ [[https://freelanderos.ru/man/1/electrics/wipers/brush_one.html <&book>Щётка - очиститель - одна]]
****_ [[https://freelanderos.ru/man/1/electrics/wipers/motor_and_linkage.html <&book>Электродвигатель и рычажный механизм - очиститель]]
****_ [[https://freelanderos.ru/man/1/electrics/wipers/lever_cleaner.html <&book>Рычаг - очиститель - снятие и установка]]
****_ [[https://freelanderos.ru/man/1/electrics/wipers/brush_cleaner.html <&book>Щётка - очиститель - снятие и установка]]
****_ [[https://freelanderos.ru/man/1/electrics/wipers/motor_cleaner.html <&book>Электродвигатель - очиститель - снятие и установка]]
****_ [[https://freelanderos.ru/man/1/electrics/wipers/combination_switch.html <&book>Комбинированный переключатель - очиститель/омыватель]]
****_ [[https://freelanderos.ru/man/1/electrics/wipers/relay_glass_cleaner_door_5.html <&book>Реле - очиститель стекла двери грузового отделения - 5-дверные модели]]
*** Омыватели
****_ [[https://freelanderos.ru/man/1/electrics/wipers/tank_washer.html <&book>Резервуар - омыватель - снятие и установка]]
****_ [[https://freelanderos.ru/man/1/electrics/wipers/injector_washer_one.html <&book>Форсунка - омыватель - одна]]
****_ [[https://freelanderos.ru/man/1/electrics/wipers/pump.html <&book>Насос - омыватель - снятие и установка]]
****_ [[https://freelanderos.ru/man/1/electrics/wipers/switch.html <&book>Переключатель - очиститель/омыватель]]
*** Навесное оборудование
**** Стартер
*****_ [[https://freelanderos.ru/man/1/electrics/engine_start/starter_td4.html <&book>Стартер - двигатель Td4]]
*****_ [[https://freelanderos.ru/man/1/electrics/engine_start/starter_kv6.html <&book>Стартер - двигатель KV6]]
*****_ [[https://freelanderos.ru/man/1/electrics/engine_start/starter_k1_8.html <&book>Стартер - двигатель K1.8]]
*****_ [[https://freelanderos.ru/man/1/electrics/engine_start/starter_relay.html <&book>Реле стартера - снятие и установка]]
**** Генератор
*****_ [[https://freelanderos.ru/man/1/electrics/engine_start/generator_td4.html <&book>Генератор - двигатель Td4]]
*****_ [[https://freelanderos.ru/man/1/electrics/engine_start/generator_kv6.html <&book>Генератор - двигатель KV6]]
*****_ [[https://freelanderos.ru/man/1/electrics/engine_start/generator_k1_8.html <&book>Генератор - двигатель K1.8]]
*** Аккумулятор
****_ [[https://freelanderos.ru/man/1/electrics/engine_start/accumulator_battery.html <&book>Аккумуляторная батарея - снятие и установка]]
****_ [[https://freelanderos.ru/man/1/electrics/engine_start/support_tray.html <&book>Опорный лоток - аккумуляторная батарея]]
****_ [[https://freelanderos.ru/man/1/electrics/engine_start/main_relay.html <&book>Главное реле - снятие и установка]]


*** Освещение
**** Фары головного света
*****_ [[https://freelanderos.ru/man/1/electrics/lighting/headlights_adjustment.html <&book>Фары головного света - пара - регулировка света - до 04MY]]
*****_ [[https://freelanderos.ru/man/1/electrics/lighting/headlights_adjustment_from_2004.html <&book>Фары головного света - пара - регулировка света - с 04MY]]
*****_ [[https://freelanderos.ru/man/1/electrics/lighting/headlamp_assembly.html <&book>Фара в сборе - модели до 04MY]]
*****_ [[https://freelanderos.ru/man/1/electrics/lighting/headlamp_assembly_from_2004.html <&book>Фара в сборе - модели с 04MY]]
*****_ [[https://freelanderos.ru/man/1/electrics/lighting/switch_adjusting_headlights.html <&book>Переключатель - регулирование света фар]]

**** Противотуманный свет
*****_ [[https://lrfreelander.ru/viewtopic.php?id=4 <&people>Форум: Противотуманный свет]]
******_ [[https://lrfreelander.ru/viewtopic.php?id=7592#p213723 <&person>Фото: Варианты установки ПТФ]]
******_ [[https://lrfreelander.ru/viewtopic.php?id=7592#p213743 <&person>Фото: Варианты установки ПТФ]]
******_ [[https://lrfreelander.ru/viewtopic.php?id=7592#p214189 <&person>Совет: На место штатных ПТФ подходят от Калины]]
*****_ [[https://lrfreelander.ru/viewtopic.php?id=7592 <&people>Форум: Выбор ПТФ]]
**** Комбинированные фонари - ПТФ+Габариты
*****_ [[https://freelanderos.ru/man/1/electrics/lighting/combined_lamp_from_2004.html <&book>Модель: 04MY]]
**** Фонари заднего хода + противотуманки
*****_ [[https://freelanderos.ru/man/1/electrics/lighting/combination_lights_rear.html <&book>Комбинированный фонарь - задний]]
*****_ [[https://freelanderos.ru/man/1/electrics/lighting/switch_rear_fog_lights.html <&book>Переключатель - задние противотуманные фонари]]
**** Поворотники
*****_ [[https://freelanderos.ru/man/1/electrics/lighting/switch_combined.html <&book>Переключатель - комбинированный, указатели поворота / света фар / звукового сигнала]]
***** Боковые
******_ [[https://freelanderos.ru/man/1/electrics/lighting/repeater_indicator.html <&book>Фонарь - повторитель указателя поворота]]
***** Задние комбинированные фонари
******_ [[https://freelanderos.ru/man/1/electrics/lighting/rear_combination_lamp.html <&book>Задний комбинированный фонарь]]
**** Стоп сигналы
***** Центральный на кронштейне запаски
******_ [[https://freelanderos.ru/man/1/electrics/lighting/central_top_stoplight.html <&book>Фонарь - центральный верхний стоп-сигнал (CHMSL)]]
**** Освещение номера
*****_ [[https://freelanderos.ru/man/1/electrics/lighting/license_plate_illumination.html <&book>Фонарь - освещение номерного знака]]
**** Освещение бардачка
*****_ [[https://freelanderos.ru/man/1/electrics/lighting/lantern_glovebox.html <&book>Фонарь - перчаточный ящик]]
*****_ [[https://freelanderos.ru/man/1/electrics/lighting/switch_glovebox.html <&book>Переключатель - перчаточный ящик]]
**** Осведение багажника
*****_ [[https://freelanderos.ru/man/1/electrics/lighting/lantern_load_compartment.html <&book>Фонарь - грузовое отделение]]
**** Аварийка
*****_ [[https://freelanderos.ru/man/1/electrics/lighting/switch_alarm.html <&book>Переключатель - аварийная сигнализация]]

*** Модули управления
**** Центральный модуль управления (CCU)
*****_ [[https://freelanderos.ru/man/1/electrics/modules/ccu.html <&book>Центральный модуль управления (CCU)]]
*****_ [[https://lrfreelander.ru/viewtopic.php?id=10134 <&people>Замена модуля CCU (нужно перепаивать микросхему)]]
*****_ [[https://lrfreelander.ru/viewtopic.php?id=884 <&people>Метод проверки CCU (возможно нерабочий)]]
**** Стеклоподёмники
*****_ [[https://freelanderos.ru/man/1/electrics/modules/window_lifters.html <&book>Стеклоподъёмник - снятие и установка]]
*****_ [[https://freelanderos.ru/man/1/carcass/doors/power_windows_tailgate.html <&book>Стеклоподъемник двери багажного отделения]]
**** Складывание зеркал
*****_ [[https://freelanderos.ru/man/1/electrics/modules/relays_folding_mirrors.html <&book>Реле - складывающиеся зеркала - модели с 02MY]]
*****_ [[https://freelanderos.ru/man/1/electrics/modules/control_module_folding_mirrors_before_2002.html <&book>Модуль управления - складывающиеся зеркала - модели до 02MY]]

**[#FF4C5B] <&warning*2>
*** Авто не открывается
*** Авто открывается
**** Проблемы с пуском двигателя
***** см. двигатель <&warning>
**** Нет проблем с пуском двигателя
***** Проблемы при работе двигателя
****** см. двигатель <&warning>
left side

@endmindmap